# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Image',
            field=models.CharField(default='No Picture Available. Weird!', max_length=500),
        ),
    ]
