# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Blog',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Idx',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
