# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_user_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMonth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('UserData.user_data',),
        ),
        migrations.CreateModel(
            name='ReportToday',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('UserData.user_data',),
        ),
        migrations.CreateModel(
            name='ReportYear',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('UserData.user_data',),
        ),
    ]
